name: Build and Deploy Unity Server

on:
  push:
    branches:
      - dev  # or any branch you'd like to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other OSes as well

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Restore Library Cache
      uses: actions/cache@v4
      with:
        path: Library
        key: Library-PFE
        restore-keys: |
          Library-PFE
          Library

    - name: Building Client
      uses: game-ci/unity-builder@v4.3.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        buildMethod: MedievalRacingBuildPipeline.BuildGameForWindows
        unityVersion: '2022.3.47f1'

    - name: Saving Client Build
      uses: actions/upload-artifact@v3
      with:
        name: MedievalRacing
        path: ./Builds/Client/*

    - name: Restore Library Cache
      uses: actions/cache@v4
      with:
        path: Library
        key: Library-PFE
        restore-keys: |
          Library-PFE
          Library

    - name: Building Server
      uses: game-ci/unity-builder@v4.3.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        buildMethod: MedievalRacingBuildPipeline.BuildServerForLinux
        unityVersion: '2022.3.47f1'
        
    - name: Saving Server Build
      uses: actions/upload-artifact@v3
      with:
        name: MedievalRacingServer
        path: ./Builds/Server/*

    - name: Deploy to VM
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i $PRIVATE_KEY -o StrictHostKeyChecking=no jlenoir@157.159.195.98 "mkdir -p /home/jlenoir/server && rm -rf /home/jlenoir/server_lastest_version/*"
        scp -i $PRIVATE_KEY -r ./Builds/Server/* jlenoir@157.159.195.98:/home/jlenoir/server_lastest_version
        ssh -i $PRIVATE_KEY -o StrictHostKeyChecking=no jlenoir@157.159.195.98 "/home/jlenoir/scripts/hooks/new_version_available.sh"
