name: Build and Deploy Unity Server

on:
  push:
    branches:
      - main  # or any branch you'd like to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other OSes as well

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-actions/setup@v2
      with:
        version: '2022.3.47f1'  # Use the Unity version you need

    - name: Build the server
      run: |
        /usr/bin/Unity -batchmode -nographics -quit -projectPath ${{ github.workspace }} -executeMethod BuildScript.BuildServer -buildTarget StandaloneLinux64 -logFile build.log

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: unity-server-build
        path: ./Build/*  # Adjust the path if necessary

    - name: Deploy to VM
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i $PRIVATE_KEY -o StrictHostKeyChecking=no jlenoir@157.159.195.98 "mkdir -p /jlenoir/home/server && rm -rf /jlenoir/home/server/*"
        scp -i $PRIVATE_KEY -r ./Build/* jlenoir@157.159.195.98:/jlenoir/home/server
        ssh -i $PRIVATE_KEY -o StrictHostKeyChecking=no jlenoir@157.159.195.98 "cd /jlenoir/home/server && nohup /jlenoir/home/server/server.x86_64 &"
